Override ParameterHandler.__getitem__
openforcefield/openforcefield pull request #753
Opened 2020-10-27 21:42 UTC by mattwthompson

Resolves  #599. Not a blocker for System work but it's really nice to be able to do `forcefield[handler_name][smirks]` to directly look up a parameter. The only lookup route is SMIRKS; other  types fail and strings that aren't parsed as SMIRKS (i.e. `id`) go nowhere.

- [x] Tag issue being addressed
- [x] Add [tests](https://github.com/openforcefield/openforcefield/tree/master/openforcefield/tests)
- [ ] Update docstrings/[documentation](https://github.com/openforcefield/openforcefield/tree/master/docs), if applicable
- [x] [Lint](https://open-forcefield-toolkit.readthedocs.io/en/latest/developing.html#style-guide) codebase
- [ ] Update [changelog](https://github.com/openforcefield/openforcefield/blob/master/docs/releasehistory.rst)

2020-11-06 18:09 UTC, j-wags requested changes
Is there any downside to consolidating all of this logic in `ParameterList.__getitem__`, and routing `ParameterHandler.__getitem__` straight to that? I think that would reduce complexity (and I'd be happy to make this change if you approve)

2020-11-09 19:31 UTC, mattwthompson commented on openforcefield/typing/engines/smirnoff/parameters.py
> +            elif len(params) > 1:  # Can this ever be hit?
Bumping this as the `ParameterList` implementation may or may not catch this in the same way. Far from blocking IMHO

2020-11-09 19:33 UTC, mattwthompson commented
The `ParameterList.__getitem__` implementation seems better; simpler with less duplicated code, and exhibited similar behavior to what is in the new tests.

Note I changed some default exceptions to `ParameterLookupError` or something like that

2020-11-09 22:40 UTC, j-wags approved these changes
Awesome. Thanks for integrating my proposal -- I hope this reduces redundancy a bit!

Please list the `IndexError` --> `ParameterLookupError` change under `Behavior Changed` in the release notes, then this should be ready to merge!

2020-11-10 00:57 UTC, merged